"""Rasterize only UI glyphs. Reproduction input: Noto Sans SC (SIL OFL)."""
from pathlib import Path
import hashlib
import urllib.request
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
cache = root / 'build'
cache.mkdir(exist_ok=True)
font_path = cache / 'NotoSansSC.ttf'
source = 'https://raw.githubusercontent.com/google/fonts/main/ofl/notosanssc/'
if not font_path.exists():
    urllib.request.urlretrieve(source + 'NotoSansSC%5Bwght%5D.ttf', font_path)
license_path = root / 'docs' / 'FONT-LICENSE.txt'
if not license_path.exists():
    urllib.request.urlretrieve(source + 'OFL.txt', license_path)
font = ImageFont.truetype(str(font_path), 12)
font.set_variation_by_axes([400])
chars = set(chr(i) for i in range(32, 127))
for p in sorted((root / 'src').glob('*.cpp')):
    chars.update(c for c in p.read_text() if ord(c) > 127)
lines = ['// Generated by tools/make_font.py; Noto Sans SC, SIL OFL. See docs/FONT-LICENSE.txt.',
         '// Source SHA256: ' + hashlib.sha256(font_path.read_bytes()).hexdigest(),
         '#pragma once', '#include <cstdint>', '#include <cstddef>',
         'namespace pond {', 'struct Glyph { uint32_t code; uint16_t rows[12]; };',
         'static constexpr Glyph Glyphs[] = {']
for char in sorted(chars):
    im = Image.new('L', (12, 12))
    # Font ascender baseline kept identical across all glyphs.
    ImageDraw.Draw(im).text((0, -3), char, font=font, fill=255)
    rows = [sum((1 << x) for x in range(12) if im.getpixel((x, y)) >= 130) for y in range(12)]
    lines.append('{%d,{%s}},' % (ord(char), ','.join(hex(v) for v in rows)))
lines += ['};', 'static constexpr size_t GlyphCount = sizeof(Glyphs) / sizeof(Glyphs[0]);', '}']
(root / 'include' / 'font_data.h').write_text('\n'.join(lines) + '\n')
print(f'{len(chars)} glyphs, {len(chars)*28} bytes including codepoints/alignment (no full CJK font in firmware)')
